sources:
    - .
templates:
  - ../Tools/SourceryTemplates
output:
  CodeGen
args:
  imports: ["MonitoredAppMiddleware", "MultipeerConnectivity", "MultipeerMiddleware", "SwiftRex", "SwiftRexMonitorEngine"]
  testable-imports: []
